
export const AUTHSTART='AUTHSTART'
export const AUTHSUCCESS='AUTHSUCCESS'
export const AUTHFAIL='AUTHFAIL'
export const LOGOUT='LOGOUT'

export const FILEUPLOAD='FILEUPLOAD'
export const FILEUPLOADDONE='FILEUPLOADDONE' 